// js/lang.js
// === Dynamic Multilingual Support for MNIMIS.GR ===

// Πίνακας μεταφράσεων
const translations = {
  gr: {
    login: "Σύνδεση",
    register: "Εγγραφή",
    logout: "Αποσύνδεση",
    welcome: "Καλώς ήρθατε στο MNIMIS.GR",
    search: "Αναζήτηση",
    register_title: "Εγγραφή Χρήστη",
    login_title: "Σύνδεση Χρήστη",
    email: "Email:",
    password: "Κωδικός:",
    register_btn: "Εγγραφή",
    register_google: "Εγγραφή με Google",
    have_account: "Έχετε ήδη λογαριασμό; Συνδεθείτε.",
    login_btn: "Σύνδεση",
    login_google: "Σύνδεση με Google",
    no_account: "Δεν έχετε λογαριασμό; Εγγραφείτε.",
    memorial_title: "Σελίδα Μνήμης",
    watch_video: "Δείτε το βίντεο",
    comments: "Σχόλια / Ευχές",
    comment_placeholder: "Γράψτε μια ευχή...",
    submit_comment: "Υποβολή",
    download_pdf: "Κατέβασμα Memorial (PDF)",
    generate_qr: "QR Code",
    report: "Αναφορά Memorial",
    partner_register_title:"Εγγραφή Συνεργάτη",
    partner_register:"Εγγραφή Συνεργάτη",
    enter_partner_code:"Εισάγετε τον Κωδικό Συνεργάτη: ",
    verify:"Επαλήθευση",
    delete_memorial:"Διαγραφή Memorial",
    view_logs:"Προβολή Αλλαγών",
    log_history:"Ιστορικό Αλλαγών"
  },
  en: {
    login: "Login",
    register: "Register",
    logout: "Logout",
    welcome: "Welcome to MNIMIS.GR",
    search: "Search",
    register_title: "User Registration",
    login_title: "User Login",
    email: "Email:",
    password: "Password:",
    register_btn: "Register",
    register_google: "Register with Google",
    have_account: "Already have an account? Login.",
    login_btn: "Login",
    login_google: "Login with Google",
    no_account: "Don't have an account? Register.",
    memorial_title: "Memorial Page",
    watch_video: "Watch Video",
    comments: "Comments / Wishes",
    comment_placeholder: "Write a wish...",
    submit_comment: "Submit",
    download_pdf: "Download Memorial (PDF)",
    generate_qr: "QR Code",
    report: "Report Memorial",
    partner_register_title:"Partner Registration",
    partner_register:"Partner Registration",
    enter_partner_code:"Enter Partner Code: ",
    verify:"Verify",
    delete_memorial:"Delete Memorial",
    view_logs:"View Changes",
    log_history:"Changed Log"
  },
  al: {
    login: "Hyrje",
    register: "Regjistrohu",
    logout: "Dil",
    welcome: "Mirë se vini në MNIMIS.GR",
    search: "Kërko",
    register_title: "Regjistrimi i Përdoruesit",
    login_title: "Hyrje e Përdoruesit",
    email: "Email:",
    password: "Fjalëkalimi:",
    register_btn: "Regjistrohu",
    register_google: "Regjistrohu me Google",
    have_account: "Keni llogari? Hyni.",
    login_btn: "Hyrje",
    login_google: "Hyr me Google",
    no_account: "Nuk keni llogari? Regjistrohuni.",
    memorial_title: "Faqja Përkujtimore",
    watch_video: "Shiko Videon",
    comments: "Komente / Urime",
    comment_placeholder: "Shkruani një urim...",
    submit_comment: "Dërgo",
    download_pdf: "Shkarko Memorialin (PDF)",
    generate_qr: "Kodi QR",
    report: "Raporto Memorialin",
    partner_register_title:"Regjistrimi i Partnerit",
    partner_register:"Regjistrohu si Partner",
    enter_partner_code:"Shkruani Kodin e Partnerit: ",
    verify:"Verifiko",
    delete_memorial:"Fshij Memorialin",
    view_logs:"Shiko Ndryshimet",
    log_history:"Historiku i Ndryshimeve"
  },
  bg: {
    login: "Вход",
    register: "Регистрация",
    logout: "Изход",
    welcome: "Добре дошли в MNIMIS.GR",
    search: "Търсене",
    register_title: "Регистрация на потребител",
    login_title: "Вход на потребител",
    email: "Имейл:",
    password: "Парола:",
    register_btn: "Регистрация",
    register_google: "Регистрация с Google",
    have_account: "Вече имате акаунт? Влезте.",
    login_btn: "Вход",
    login_google: "Вход с Google",
    no_account: "Нямате акаунт? Регистрирайте се.",
    memorial_title: "Мемориална страница",
    watch_video: "Гледай видеото",
    comments: "Коментари / Пожелания",
    comment_placeholder: "Напишете пожелание...",
    submit_comment: "Изпрати",
    download_pdf: "Изтегли Мемориала (PDF)",
    generate_qr: "QR код",
    report: "Докладвай Мемориал",
    partner_register_title:"Регистрация на Партньор",
    partner_register:"Регистриране като Партньор",
    enter_partner_code:"Въведете кода на партньора: ",
    verify:"Провери",
    delete_memorial:"Изтрий Мемориала",
    view_logs:"Преглед на промените",
    log_history:"История на промените"
  },
  ru: {
    login: "Войти",
    register: "Регистрация",
    logout: "Выйти",
    welcome: "Добро пожаловать в MNIMIS.GR",
    search: "Поиск",
    register_title: "Регистрация пользователя",
    login_title: "Вход пользователя",
    email: "Эл. почта:",
    password: "Пароль:",
    register_btn: "Зарегистрироваться",
    register_google: "Регистрация через Google",
    have_account: "Уже есть аккаунт? Войти.",
    login_btn: "Войти",
    login_google: "Войти через Google",
    no_account: "Нет аккаунта? Зарегистрируйтесь.",
    memorial_title: "Страница памяти",
    watch_video: "Смотреть видео",
    comments: "Комментарии / Пожелания",
    comment_placeholder: "Напишите пожелание...",
    submit_comment: "Отправить",
    download_pdf: "Скачать Мемориал (PDF)",
    generate_qr: "QR код",
    report: "Пожаловаться на Мемориал",
    partner_register_title:"Регистрация Партнёра",
    partner_register:"Зарегистрироваться как Партнёр",
    enter_partner_code:"Введите код партнёра: ",
    verify:"Проверить",
    delete_memorial:"Удалить Мемориал",
    view_logs:"История изменений",
    log_history:"История изменений"
  }
};

// Ορισμός και εφαρμογή γλώσσας
function setLanguage(lang) {
  localStorage.setItem("lang", lang);
  updateLanguage();
}

function updateLanguage() {
  const lang = localStorage.getItem("lang") || "gr";
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      el.innerText = translations[lang][key];
    }
  });
}

window.setLanguage = setLanguage;
window.addEventListener("DOMContentLoaded", updateLanguage);
