// js/lang.js
const translations={
  en:{site_title:"MNIMIS.GR",home_title:"Digital Memorial Pages",home_description:"Create lasting tributes with QR/NFC technology.",get_started:"Get Started",register_title:"Register | MNIMIS.GR",login_title:"Login | MNIMIS.GR",dashboard_title:"Dashboard",memorial_title:"Memorial Page",admin_title:"Admin Panel",register_heading:"Create Account",login_heading:"Login",email_label:"Email:",password_label:"Password:",role_label:"Role:",role_funeral:"Funeral Home",role_relative:"Relative",register_button:"Register",login_button:"Login",have_account:"Already have account?",no_account:"Don't have an account?",dashboard_heading:"Welcome,",create_memorial:"Create Memorial",manage_memorials:"Manage Memorials",report_button:"Report Page",comments_heading:"Comments & Wishes",post_comment:"Post Comment",pending_memorials:"Pending Memorials",pending_offices:"Pending Offices",ads_control:"Advertisements"},
  el:{site_title:"MNIMIS.GR",home_title:"Ψηφιακές Σελίδες Μνήμης",home_description:"Δημιουργήστε και μοιραστείτε ηλεκτρονικά μνημόσυνα.",get_started:"Ξεκίνα",register_title:"Εγγραφή | MNIMIS.GR",login_title:"Είσοδος | MNIMIS.GR",dashboard_title:"Πίνακας Ελέγχου",memorial_title:"Σελίδα Μνήμης",admin_title:"Διαχείριση",register_heading:"Δημιουργία Λογαριασμού",login_heading:"Σύνδεση",email_label:"Email:",password_label:"Κωδικός:",role_label:"Είδος Χρήστη:",role_funeral:"Γραφείο Κηδειών",role_relative:"Συγγενής",register_button:"Εγγραφή",login_button:"Σύνδεση",have_account:"Έχω ήδη λογαριασμό",no_account:"Δεν έχω λογαριασμό",dashboard_heading:"Καλώς ήρθες,",create_memorial:"Δημιουργία Memorial",manage_memorials:"Διαχείριση Memorials",report_button:"Αναφορά Σελίδας",comments_heading:"Σχόλια & Ευχές",post_comment:"Αποστολή",pending_memorials:"Εκκρεμή Memorials",pending_offices:"Εκκρεμή Γραφεία",ads_control:"Διαφημίσεις"}
};
let lang=localStorage.getItem('lang')||'el';
document.querySelectorAll('[data-lang-key]').forEach(el=>{const key=el.getAttribute('data-lang-key');el.textContent=translations[lang][key]||key;});
document.querySelectorAll('.flag').forEach(img=>img.addEventListener('click',()=>{lang=img.dataset.lang;localStorage.setItem('lang',lang);document.querySelectorAll('[data-lang-key]').forEach(el=>{const key=el.getAttribute('data-lang-key');el.textContent=translations[lang][key]||key;});}));


// js/ui.js
export function showLoader(){let l=document.getElementById('loader-overlay');if(!l){l=document.createElement('div');l.id='loader-overlay';Object.assign(l.style,{position:'fixed',top:0,left:0,width:'100%',height:'100%',background:'rgba(0,0,0,0.5)',display:'flex',justifyContent:'center',alignItems:'center'});l.innerHTML='<div class="spinner"></div>';document.body.appendChild(l);}l.style.display='flex';}
export function hideLoader(){const l=document.getElementById('loader-overlay');if(l)l.style.display='none';}
export function displayAlert(msg,type='info'){const a=document.createElement('div');Object.assign(a.style,{position:'fixed',top:'1rem',left:'50%',transform:'translateX(-50%)',padding:'0.75rem 1.5rem',borderRadius:'0.375rem',backgroundColor:type==='error'?'#ff4d4f':type==='success'?'#52c41a':'#0055A5',color:'#fff',zIndex:1000,fontFamily:'Roboto, sans-serif',fontSize:'1rem',boxShadow:'0 2px 6px rgba(0,0,0,0.2)'});a.textContent=msg;document.body.appendChild(a);setTimeout(()=>a.remove(),3000);}
export async function generateQRCode(cid,text){const c=document.getElementById(cid);c.innerHTML='';new QRCode(c,{text,width:128,height:128});}
const savedTheme=localStorage.getItem('theme');if(savedTheme)document.documentElement.setAttribute('data-theme',savedTheme);
export function toggleDarkMode(){const c=document.documentElement.getAttribute('data-theme')||'light',n=c==='light'?'dark':'light';document.documentElement.setAttribute('data-theme',n);localStorage.setItem('theme',n);}export function sanitize(input){return DOMPurify.sanitize(input);}
